### ISSUE TITLE
Unable to find precomputed `.npz`

### ISSUE THREAD

**Issue by mitkotak** [atomicarchitects/BasisLib#1]
This affects all functions that use `lookup_table_generation_utility.py`

```python
import BasisLib
BasisLib.so3.clebsch_gordan_for_degrees(1,1,2)
```

```
ERROR:absl:Failed to load pre-computed Clebsch-Gordan lookup table included with the BasisLib.so3.lookup_table_generation_utility package (data may be corrupted). Consider re-installing the package to fix this problem.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/BasisLib/so3/lookup_table_generation_utility.py", line 50, in _load_lookup_table_from_disk
    return load_from_cache(f)
  File "/usr/local/lib/python3.10/dist-packages/BasisLib/so3/clebsch_gordan_lut.py", line 72, in _load_from_cache
    with np.load(f) as cache:
  File "/usr/local/lib/python3.10/dist-packages/numpy/lib/npyio.py", line 462, in load
    raise ValueError("Cannot load file containing pickled data "
ValueError: Cannot load file containing pickled data when allow_pickle=False
```

**Comment by mitkotak** [comment]
Resolved in https://github.com/atomicarchitects/BasisLib/commit/cb3c4ee27db72d2df9f928200f086b89f5b8c152
